### ISSUE TITLE
License for the project

### ISSUE THREAD

**Issue by anishsheela** [speakforme/frontend#148]
The license is not specified in the project.

I want to reuse some of the code for an opensource project for @smc . So, can you people specify the license so that I can determine whether I can reuse safely for my project?

**Comment by jace** [comment]
Assigning this to @captn3m0 as he's the primary author.

**Comment by captn3m0** [comment]
MIT should work well here, right?

**Comment by captn3m0** [comment]
@aravindet @championswimmer going ahead with MIT unless you have any objections.

**Comment by aravindet** [comment]
No issues from my side.

Aravind
