### ISSUE TITLE
Language switcher not showing current language on load

### ISSUE THREAD

**Issue by planemad** [speakforme/frontend#52]
<img width="312" alt="screen shot 2017-12-13 at 3 55 09 pm" src="https://user-images.githubusercontent.com/126868/33934187-213ded44-e01e-11e7-8469-d762279945c5.png">

- When the site loads, the language selector is blank
- This should instead show the set language

**Comment by siddhesh** [comment]
https://github.com/speakforme/frontend/pull/51 should fix it.

**Comment by siddhesh** [comment]
Merged.
