### ISSUE TITLE
When you post a link to https://www.speakforme.in on Facebook, the headline for that post should be more transparent and compelling

### ISSUE THREAD

**Issue by Kream** [speakforme/frontend#63]
Currently, it is merely 
![screen shot 2017-12-13 at 19 21 25](https://user-images.githubusercontent.com/738161/33942119-efd5629c-e03a-11e7-9f77-ccc948580288.png)
It should instead be more understandable and compelling. Say, something like "Contact your MP, Bank or Service Provider about Aadhaar"

**Comment by aravindet** [comment]
Now it says "Opt out. Tell service providers to delink your Aadhaar".
