### ISSUE TITLE
Thumbnail image for previews

### ISSUE THREAD

**Issue by karthikb351** [speakforme/frontend#95]
Currently, there is no thumbnail image when sharing the website like on sites.

A 1200px x 630px image will be ideal, with the design keeping in mind that in some places the thumbnails get cropped to the center square (like WhatsApp).

Metatags for Facebook and Twitter were added with #94. Once this issue is resolved, we can uncomment the image meta tags.

```
<--------------1200x630-------------> 
+-------------------------------------+
|         |                 |         |
|         |                 |         |
|         |                 |         |
|         |   #SpeakForMe   |         |
|<--285-->|                 |<--285-->|
|         |                 |         |
|         |  speakforme.in  |         |
|         |                 |         |
|         |                 |         |
+-------------------------------------+
```

**Comment by hfactor** [comment]
@karthikb351 Attaching two images. 1200x630 size.

![og-speakforme in](https://user-images.githubusercontent.com/1788677/34002241-1784057c-e118-11e7-9f89-03de6fc3dfce.png)
![og-speakforme](https://user-images.githubusercontent.com/1788677/34002248-1b8ddc92-e118-11e7-915b-f5d96e1a4889.png)

**Comment by hfactor** [comment]
@karthikb351 
two options. have a look.


![og-speakforme in](https://user-images.githubusercontent.com/1788677/34002315-4a37758a-e118-11e7-804d-b8bcfd220f9c.png)
![og-speakforme](https://user-images.githubusercontent.com/1788677/34002319-4c85f28a-e118-11e7-82ac-9571437223a7.png)

**Comment by jace** [comment]
@hfactor thanks, but we settled on this version earlier. Could you build on it? The logo is meant to be a `#`.

![logo](https://user-images.githubusercontent.com/26695/34002510-c43a684c-e118-11e7-8e6d-1c8237715146.png)

**Comment by hfactor** [comment]
@jace Have a look. 

![og-speakforme](https://user-images.githubusercontent.com/1788677/34002870-cb69721a-e119-11e7-8b16-7a3dcb583e61.png)
