### ISSUE TITLE
Specific URLs for each language?

### ISSUE THREAD

**Issue by dthomas** [speakforme/frontend#97]
Can we have a specific language pre-selected via url?

Eg: speakforme.in/en/ -> The entire site is in English
speakforme.in/hi/ -> The entire site is in Hindi

Use case:

Easy to target regional campaigns, for people without English knowledge, this will enable them to see the entire site in their local language and respond.

**Comment by captn3m0** [comment]
We do support it: https://www.speakforme.in/mp/?lang=ta

If someone has already selected a language on a previous visit

**Comment by dthomas** [comment]
> If someone has already selected a language on a previous visit

Or hasn't? I visit that page, it shows up everything in Tamizh, if I change URL to =lang=ml, it doesn't work

**Comment by captn3m0** [comment]
Once you reach a pre-selected URL, we store it as your preference, if you refresh after that, it will use your changed preference.

/cc @championswimmer for more details

**Comment by siddhesh** [comment]
Here's a proposed patch which should make the interaction a bit more predictable.  What do y'all think about it?

**Comment by dthomas** [comment]
Perfect! Thank you! :100:
